---
title: "Exploring cfbfastR package"
output: html_notebook
---

```{r libraries, include=TRUE}
library(tidyverse)
library(gt)
library(cfbfastR)

# You can install using the pacman package using the following code:
# if (!requireNamespace('pacman', quietly = TRUE)){
#   install.packages('pacman')
# }
# pacman::p_load_current_gh("sportsdataverse/cfbfastR", dependencies = TRUE, update = TRUE)
```

```{r}
wvu_pbp_2025 <- cfbfastR::cfbd_pbp_data(year = 2025,
                                        season_type = 'regular',
                                        week = 3,
                                        team = 'West Virginia',
                                        epa_wpa = TRUE) %>% 
  janitor::clean_names()
```

```{r}
wvu_pbp_2025 %>% 
  select(play_text, epa, wpa) %>% 
  filter(wpa > .05 & wpa < .95) %>% 
  top_n(10, abs(epa)) %>% 
  arrange(-abs(epa))
```

```{r}
wvu_pbp_2025 %>% 
  distinct(play_type)
```

```{r}
wvu_pbp_2025 %>% 
  arrange(game_play_number)
  filter(play_type == 'Interception Return')
```



```{r}
wvu_pbp_2025 <- wvu_pbp_2025 %>%
  mutate(play_type_agg = case_when(
    play_type %in%  c('Pass Incompletion', 'Pass Reception', 'Sack', 
                      'Interception Return', 'Passing Touchdown') ~ "pass",
    play_type %in% c('Rush', 'Rushing Touchdown') ~ "rush",
    TRUE ~ 'other'   # fallback/default
  )) %>% 
  select(play_type, play_type_agg, everything())
```



```{r}
wvu_pbp_2025 %>% 
  # filter(play_type == 'Punt')
  # distinct(play_type)
  # select(contains('epa'))
  group_by(pos_team, play_type_agg) %>% 
  summarise(success_rate = mean(success, na.rm = TRUE),
            epa_success_rate = mean(epa_success, na.rm = TRUE),
            epa_per_play = mean(epa, na.rm = TRUE))
```



## Coaches 


```{r}
coaches <- cfbfastR::cfbd_coaches()

wv_coaches <- cfbfastR::cfbd_coaches() %>% 
  filter(school == 'West Virginia')

coaches %>% 
  mutate(name = paste(first_name, last_name, sep=' ')) %>% 
  filter(year >= 2001) %>% 
  group_by(name) %>% 
  summarise(across(c('wins', 'losses', 'ties'),
                   list(
                     sum = ~sum(., na.rm = TRUE)
                   ),
                   .names = "{.fn}_{.col}"
                   ),
            seasons = n_distinct(year),
            max_wins = max(wins), 
            min_wins = min(wins), 
            first_season = min(year),
            last_season = max(year),
            .groups = 'drop') %>% 
  mutate(avg_wins_per_season = round(sum_wins / seasons, 1),
         rank_wins = rank(-sum_wins),
         win_perc = sum_wins / (sum_wins + sum_losses + sum_ties)) %>% 
  arrange(-win_perc) %>% 
  select(name, rank_wins, everything())
  filter(first_name == 'Rich' & last_name == 'Rodriguez')
```

```{r}
wv_coaches %>% 
  mutate(name = paste(first_name, last_name, sep=' ')) %>% 
  group_by(name) %>% 
  summarise(across(c('wins', 'losses', 'ties'),
                   list(
                     sum = ~sum(., na.rm = TRUE)
                   ),
                   .names = "{.fn}_{.col}"
                   ),
            seasons = n_distinct(year),
            max_wins = max(wins), 
            first_season = min(year),
            last_season = max(year),
            .groups = 'drop') %>% 
  mutate(avg_wins_per_season = round(sum_wins / seasons, 1)) %>% 
  arrange(-sum_wins)
```

```{r}
wv_season_stats <- cfbfastR::cfbd_stats_season_advanced(year = 2002, team = 'West Virginia')
```


```{r get_wv_season_stats, include=TRUE}
seasons <- 2001:2024

get_wv_stats <- function(season){
  cfbd_stats_season_team(year = season, team = 'West Virginia') %>% 
    # adds the season as a column to the dataframe
    mutate(season = season) %>% 
    # moves the season column to the first position, then selects every other column in order
    # could also use relocate() but I prefer select()
    select(season, everything())
}

wv_stats_2001_24 <- map_df(seasons, get_wv_stats)
```

```{r}
wv_stats_2001_24 %>% 
  relocate(team)
```



